/**
 * Knowledge Base Chunks for Marine Science, INCOIS PFZ Advisories & Ocean Dynamics (RAG)
 * Strictly factual, sourced, and zero emojis.
 */

export interface KnowledgeChunk {
  id: string;
  title: string;
  topic: 'pfz' | 'safety' | 'sst_dynamics' | 'chlorophyll' | 'cyclones' | 'regulations';
  source: string;
  published: string;
  content: string;
  tags: string[];
}

export const KNOWLEDGE_CHUNKS: KnowledgeChunk[] = [
  {
    id: 'incois-pfz-gen',
    title: 'Generation of Potential Fishing Zone (PFZ) Advisories',
    topic: 'pfz',
    source: 'Indian National Centre for Ocean Information Services (INCOIS)',
    published: '2024-03-15',
    content: 'INCOIS generates Potential Fishing Zone (PFZ) advisories using composite satellite data of Sea Surface Temperature (SST) from AVHRR/MODIS and Chlorophyll-a concentrations from Oceansat-3 OCM. Thermal gradients (fronts) and chlorophyll eddies indicate nutrient-rich upwelling zones where pelagic species like sardines, mackerel, and tuna aggregate.',
    tags: ['PFZ', 'INCOIS', 'Thermal Fronts', 'Upwelling', 'Fish Aggregation']
  },
  {
    id: 'incois-cloud-fallback',
    title: 'Cloud Cover Fallback Strategy for Ocean Color Sensors',
    topic: 'chlorophyll',
    source: 'INCOIS Marine Oceanography Division',
    published: '2023-11-10',
    content: 'During monsoon periods (June to September) over the Arabian Sea and Bay of Bengal, optical ocean color sensors (Chlorophyll-a) experience data gaps exceeding 60-80% due to persistent cloud cover. In such scenarios, ORCA automatically switches to microwave SST reanalysis (which penetrates cloud cover) and high-resolution numerical hydrodynamic model currents to locate divergence and frontal zones.',
    tags: ['Chlorophyll', 'Cloud Cover', 'Microwave SST', 'Monsoon', 'Fallback']
  },
  {
    id: 'kerala-catch-decline-reasons',
    title: 'Ecological Drivers of Oil Sardine Catch Fluctuations in Southwest India',
    topic: 'sst_dynamics',
    source: 'Central Marine Fisheries Research Institute (CMFRI) Special Publication No. 128',
    published: '2023-08-20',
    content: 'Oil sardine (Sardinella longiceps) landings along the Kerala and Karnataka coast exhibit strong decadal oscillations linked to the Indian Ocean Dipole (IOD) and El Niño Southern Oscillation (ENSO). Rising SST above 29.5 deg C during pre-monsoon triggers thermal stratification, restricting nutrient upwelling and suppressing diatom blooms, causing sardines to migrate to deeper waters or northward to Maharashtra.',
    tags: ['Kerala', 'Oil Sardine', 'CMFRI', 'Thermal Stratification', 'Catch Decline']
  },
  {
    id: 'swell-surge-warning',
    title: 'Swell Surge (Kallakkal) Dynamics along the Southern Coast',
    topic: 'safety',
    source: 'INCOIS Ocean State Forecast Operations',
    published: '2024-01-12',
    content: 'Kallakkal or Swell Surge events occur without local wind activity. They are generated by distant southern ocean storms (near 40 to 60 deg S latitude) that propagate across the Indian Ocean over 3 to 5 days, reaching the coasts of Kerala, Tamil Nadu, and Lakshadweep with wave periods exceeding 14 to 20 seconds. These long-period swells cause sudden devastating coastal flooding and harbor turbulence.',
    tags: ['Swell Surge', 'Kallakkal', 'Long-Period Waves', 'Harbor Safety']
  },
  {
    id: 'cyclone-formation-criteria',
    title: 'Tropical Cyclogenesis Criteria in the North Indian Ocean',
    topic: 'cyclones',
    source: 'India Meteorological Department (IMD) Cyclone Warning Division',
    published: '2023-10-05',
    content: 'Tropical cyclogenesis requires SST >= 26.5 deg C, low vertical wind shear (< 10 m/s between 850 and 200 hPa), high mid-tropospheric relative humidity (> 60%), and enhanced low-level vorticity. In operational decision support, a sustained pressure drop of >= 6 hPa within 12 hours coupled with wind gusts >= 34 knots (Gale force) necessitates immediate red-tier vessel evacuation to port.',
    tags: ['Cyclone', 'IMD', 'Pressure Drop', 'Wind Shear', 'Gale Warning']
  },
  {
    id: 'imbl-legal-sovereignty',
    title: 'Maritime Zone Distinctions: Territorial Waters vs EEZ vs IMBL',
    topic: 'regulations',
    source: 'Maritime Zones of India Act & Indian Coast Guard Guidelines',
    published: '2022-06-18',
    content: 'India territorial sea extends up to 12 nautical miles (22.2 km) from the baseline, where coastal state sovereignty is absolute. The Exclusive Economic Zone (EEZ) extends up to 200 nautical miles (370.4 km). Crossing the International Maritime Boundary Line (IMBL) into neighboring national waters (e.g. Sri Lanka or Pakistan) violates international maritime law and risks detention.',
    tags: ['IMBL', 'EEZ', 'Territorial Sea', 'Coast Guard', 'Regulations']
  },
  {
    id: 'thermal-front-sobel',
    title: 'Mathematical Identification of Marine Thermal Fronts',
    topic: 'sst_dynamics',
    source: 'Remote Sensing of Environment (Cayula-Cornillon Framework)',
    published: '2023-04-14',
    content: 'Thermal fronts represent horizontal boundaries between distinct water masses. Algorithms compute spatial gradients using 2D Sobel operators alongside Otsu histogram bi-modal separation. Fronts with temperature gradients exceeding 0.02 deg C per kilometer and separation ratios > 0.65 exhibit strong physical shear and zooplankton trapping efficiency.',
    tags: ['Cayula-Cornillon', 'Otsu', 'Sobel Filter', 'Gradient Math', 'Physical Oceanography']
  },
  {
    id: 'gulf-mannar-biodiversity',
    title: 'Ecological Zoning in the Gulf of Mannar Biosphere Reserve',
    topic: 'regulations',
    source: 'Tamil Nadu Forest Department & Gulf of Mannar Biosphere Reserve Trust',
    published: '2023-02-11',
    content: 'The Gulf of Mannar Marine National Park encompasses 21 islands along Mandapam to Tuticorin. Commercial mechanized trawling and purse-seining are prohibited within the core sanctuary zone to protect fragile Acropora coral reefs, sea cow (Dugong dugon) habitats, and endangered sea turtles. Artisanal non-destructive gear is restricted to designated buffer zones.',
    tags: ['Gulf of Mannar', 'Marine Sanctuary', 'Coral Reef', 'Conservation', 'Zoning']
  },
  {
    id: 'rough-sea-scale',
    title: 'WMO Sea State and Significant Wave Height Classifications',
    topic: 'safety',
    source: 'World Meteorological Organization (WMO) Code 3700',
    published: '2024-02-01',
    content: 'Significant wave height (Hs) classifications: Calm-Glassy (0 m), Calm-Rippled (0-0.1 m), Smooth (0.1-0.5 m), Slight (0.5-1.25 m), Moderate (1.25-2.5 m), Rough (2.5-4.0 m), Very Rough (4.0-6.0 m), High (6.0-9.0 m), Very High (9.0-14.0 m), Phenomenal (> 14.0 m). Non-mechanised vessels must never operate beyond Moderate sea state (Hs > 1.5 m).',
    tags: ['Sea State', 'WMO', 'Significant Wave Height', 'Vessel Limits']
  },
  {
    id: 'gujarat-deepsea-demersal',
    title: 'Demersal Trawl Dynamics in the Saurashtra Basin',
    topic: 'pfz',
    source: 'Fishery Survey of India (FSI) Annual Demersal Assessment',
    published: '2023-12-04',
    content: 'The continental shelf off Gujarat is the widest in India, spanning up to 350 km. High demersal productivity for ribbonfish, croakers, and cuttlefish is sustained by tidal mixing and sediment-rich nutrient resuspension. Trawlers must navigate carefully around the 50-meter depth contour near the Sir Creek delta to prevent international drift during nocturnal operations.',
    tags: ['Gujarat', 'Saurashtra', 'Trawling', 'Demersal', 'Sir Creek']
  }
];

export function searchKnowledgeBase(query: string, limit = 4): KnowledgeChunk[] {
  const terms = query.toLowerCase().split(/\s+/).filter(t => t.length > 2);
  if (terms.length === 0) return KNOWLEDGE_CHUNKS.slice(0, limit);

  const scored = KNOWLEDGE_CHUNKS.map(chunk => {
    let score = 0;
    const titleLower = chunk.title.toLowerCase();
    const contentLower = chunk.content.toLowerCase();
    const tagsLower = chunk.tags.map(t => t.toLowerCase()).join(' ');

    for (const t of terms) {
      if (titleLower.includes(t)) score += 5;
      if (tagsLower.includes(t)) score += 3;
      if (contentLower.includes(t)) score += 1;
    }
    return { chunk, score };
  });

  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.chunk);
}
